### PR TITLE
change parse_mode to markdownV2

### PR DESCRIPTION
**Pull request by marchingon12**
Test if parse mode changes to markdownV2 or not

### CODE REVIEW

**Comment by marchingon12** [comment]
confirmed parse_mode changes to markdownV2. Trying to make 'Building' bold text and hyperlinked failed, will try with next commit.

**Comment by marchingon12** [comment]
confirmed that '*bold \*Building*' maked text bold and hypelinked, however 'bold \*' are included with hyperlink unnecessarily. Will make third attempt in next commit.

**Comment by marchingon12** [comment]
confirmed successfully made text 'Building' hyperlink and bold with markdownV2.

**Comment by marchingon12** [comment]
Confirmed commit hash is bold and hyperlinked after building. Ready to merge :heavy_check_mark:

**Comment by theradcolor** [comment]
> Confirmed commit hash is bold and hyperlinked after building. Ready to merge ✔️

👍

**Pull request merged**
